create table if not exists public.billing_rates (
  month text primary key,
  storage_rate numeric not null default 6,
  inbound_rate numeric not null default 10,
  outbound_rate numeric not null default 10,
  updated_at timestamptz not null default now()
);

create table if not exists public.charge_invoices (
  id bigint generated by default as identity primary key,
  month text not null,
  file_name text not null,
  file_url text not null,
  status text not null default 'PAID',
  created_at timestamptz not null default now()
);

create table if not exists public.monthly_charge_summaries (
  month text primary key,
  storage_subtotal numeric not null default 0,
  inbound_subtotal numeric not null default 0,
  outbound_subtotal numeric not null default 0,
  total numeric not null default 0,
  weekly jsonb not null default '[]'::jsonb,
  inbound jsonb not null default '[]'::jsonb,
  outbound jsonb not null default '[]'::jsonb,
  calculated_at timestamptz not null default now()
);

insert into public.billing_rates (month, storage_rate, inbound_rate, outbound_rate)
values ('2025-12', 6, 10, 10)
on conflict (month) do nothing;

insert into storage.buckets (id, name, public)
values ('charge-invoices', 'charge-invoices', true)
on conflict (id) do nothing;

alter table public.billing_rates enable row level security;
alter table public.charge_invoices enable row level security;
alter table public.monthly_charge_summaries enable row level security;

drop policy if exists "billing_rates_select_owner" on public.billing_rates;
drop policy if exists "billing_rates_insert_owner" on public.billing_rates;
drop policy if exists "billing_rates_update_owner" on public.billing_rates;
drop policy if exists "billing_rates_delete_owner" on public.billing_rates;

create policy "billing_rates_select_owner"
on public.billing_rates for select
to authenticated
using (public.current_profile_role() = 'owner');

create policy "billing_rates_insert_owner"
on public.billing_rates for insert
to authenticated
with check (public.current_profile_role() = 'owner');

create policy "billing_rates_update_owner"
on public.billing_rates for update
to authenticated
using (public.current_profile_role() = 'owner')
with check (public.current_profile_role() = 'owner');

create policy "billing_rates_delete_owner"
on public.billing_rates for delete
to authenticated
using (public.current_profile_role() = 'owner');

drop policy if exists "charge_invoices_select_owner" on public.charge_invoices;
drop policy if exists "charge_invoices_insert_owner" on public.charge_invoices;
drop policy if exists "charge_invoices_update_owner" on public.charge_invoices;
drop policy if exists "charge_invoices_delete_owner" on public.charge_invoices;

create policy "charge_invoices_select_owner"
on public.charge_invoices for select
to authenticated
using (public.current_profile_role() = 'owner');

create policy "charge_invoices_insert_owner"
on public.charge_invoices for insert
to authenticated
with check (public.current_profile_role() = 'owner');

create policy "charge_invoices_update_owner"
on public.charge_invoices for update
to authenticated
using (public.current_profile_role() = 'owner')
with check (public.current_profile_role() = 'owner');

create policy "charge_invoices_delete_owner"
on public.charge_invoices for delete
to authenticated
using (public.current_profile_role() = 'owner');

drop policy if exists "monthly_charge_summaries_select_owner" on public.monthly_charge_summaries;
drop policy if exists "monthly_charge_summaries_insert_owner" on public.monthly_charge_summaries;
drop policy if exists "monthly_charge_summaries_update_owner" on public.monthly_charge_summaries;
drop policy if exists "monthly_charge_summaries_delete_owner" on public.monthly_charge_summaries;

create policy "monthly_charge_summaries_select_owner"
on public.monthly_charge_summaries for select
to authenticated
using (public.current_profile_role() = 'owner');

create policy "monthly_charge_summaries_insert_owner"
on public.monthly_charge_summaries for insert
to authenticated
with check (public.current_profile_role() = 'owner');

create policy "monthly_charge_summaries_update_owner"
on public.monthly_charge_summaries for update
to authenticated
using (public.current_profile_role() = 'owner')
with check (public.current_profile_role() = 'owner');

create policy "monthly_charge_summaries_delete_owner"
on public.monthly_charge_summaries for delete
to authenticated
using (public.current_profile_role() = 'owner');

drop policy if exists "charge_invoices_storage_select_owner" on storage.objects;
drop policy if exists "charge_invoices_storage_insert_owner" on storage.objects;
drop policy if exists "charge_invoices_storage_update_owner" on storage.objects;
drop policy if exists "charge_invoices_storage_delete_owner" on storage.objects;

create policy "charge_invoices_storage_select_owner"
on storage.objects for select
to authenticated
using (
  bucket_id = 'charge-invoices'
  and public.current_profile_role() = 'owner'
);

create policy "charge_invoices_storage_insert_owner"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'charge-invoices'
  and public.current_profile_role() = 'owner'
);

create policy "charge_invoices_storage_update_owner"
on storage.objects for update
to authenticated
using (
  bucket_id = 'charge-invoices'
  and public.current_profile_role() = 'owner'
)
with check (
  bucket_id = 'charge-invoices'
  and public.current_profile_role() = 'owner'
);

create policy "charge_invoices_storage_delete_owner"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'charge-invoices'
  and public.current_profile_role() = 'owner'
);
