create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null check (role in ('owner', 'warehouse')),
  warehouse text,
  check (
    (role = 'owner' and warehouse is null)
    or (role = 'warehouse' and warehouse is not null)
  )
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.activities(id) on delete cascade,
  file_name text not null,
  file_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.charges (
  id bigint generated by default as identity primary key,
  month text not null,
  warehouse text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('activity-documents', 'activity-documents', true)
on conflict (id) do nothing;

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid()
$$;

create or replace function public.current_profile_warehouse()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select warehouse from public.profiles where id = auth.uid()
$$;

create or replace function public.can_access_warehouse(target_warehouse text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_profile_role() = 'owner'
    or (
      public.current_profile_role() = 'warehouse'
      and public.current_profile_warehouse() = target_warehouse
    )
$$;

alter table public.profiles enable row level security;
alter table public.activities enable row level security;
alter table public.documents enable row level security;
alter table public.charges enable row level security;

do $$
declare
  policy_record record;
begin
  for policy_record in
    select n.nspname, c.relname, p.polname
    from pg_policy p
    join pg_class c on c.oid = p.polrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname in ('activities', 'documents', 'charges')
      and p.polcmd in ('a', 'd', '*')
      and (p.polroles = '{0}'::oid[] or 'public'::regrole::oid = any(p.polroles))
  loop
    execute format('drop policy if exists %I on %I.%I', policy_record.polname, policy_record.nspname, policy_record.relname);
  end loop;

  for policy_record in
    select n.nspname, c.relname, p.polname
    from pg_policy p
    join pg_class c on c.oid = p.polrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'storage'
      and c.relname = 'objects'
      and p.polcmd in ('a', 'd', '*')
      and (p.polroles = '{0}'::oid[] or 'public'::regrole::oid = any(p.polroles))
  loop
    execute format('drop policy if exists %I on %I.%I', policy_record.polname, policy_record.nspname, policy_record.relname);
  end loop;
end $$;

drop policy if exists "profiles_select_scoped" on public.profiles;
drop policy if exists "profiles_insert_owner" on public.profiles;
drop policy if exists "profiles_update_owner" on public.profiles;
drop policy if exists "profiles_delete_owner" on public.profiles;

create policy "profiles_select_scoped"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.current_profile_role() = 'owner');

create policy "profiles_insert_owner"
on public.profiles for insert
to authenticated
with check (public.current_profile_role() = 'owner');

create policy "profiles_update_owner"
on public.profiles for update
to authenticated
using (public.current_profile_role() = 'owner')
with check (public.current_profile_role() = 'owner');

create policy "profiles_delete_owner"
on public.profiles for delete
to authenticated
using (public.current_profile_role() = 'owner');

drop policy if exists "activities_select_scoped" on public.activities;
drop policy if exists "activities_insert_scoped" on public.activities;
drop policy if exists "activities_update_scoped" on public.activities;
drop policy if exists "activities_delete_scoped" on public.activities;
drop policy if exists "public activities insert" on public.activities;
drop policy if exists "public activities delete" on public.activities;
drop policy if exists "Enable insert for public users" on public.activities;
drop policy if exists "Enable delete for public users" on public.activities;

create policy "activities_select_scoped"
on public.activities for select
to authenticated
using (public.can_access_warehouse(warehouse));

create policy "activities_insert_scoped"
on public.activities for insert
to authenticated
with check (public.can_access_warehouse(warehouse));

create policy "activities_update_scoped"
on public.activities for update
to authenticated
using (public.can_access_warehouse(warehouse))
with check (public.can_access_warehouse(warehouse));

create policy "activities_delete_scoped"
on public.activities for delete
to authenticated
using (public.can_access_warehouse(warehouse));

drop policy if exists "documents_select_scoped" on public.documents;
drop policy if exists "documents_insert_scoped" on public.documents;
drop policy if exists "documents_update_scoped" on public.documents;
drop policy if exists "documents_delete_scoped" on public.documents;
drop policy if exists "public documents insert" on public.documents;
drop policy if exists "public documents delete" on public.documents;
drop policy if exists "Enable insert for public users" on public.documents;
drop policy if exists "Enable delete for public users" on public.documents;

create policy "documents_select_scoped"
on public.documents for select
to authenticated
using (
  exists (
    select 1
    from public.activities a
    where a.id = documents.activity_id
      and public.can_access_warehouse(a.warehouse)
  )
);

create policy "documents_insert_scoped"
on public.documents for insert
to authenticated
with check (
  exists (
    select 1
    from public.activities a
    where a.id = documents.activity_id
      and public.can_access_warehouse(a.warehouse)
  )
);

create policy "documents_update_scoped"
on public.documents for update
to authenticated
using (
  exists (
    select 1
    from public.activities a
    where a.id = documents.activity_id
      and public.can_access_warehouse(a.warehouse)
  )
)
with check (
  exists (
    select 1
    from public.activities a
    where a.id = documents.activity_id
      and public.can_access_warehouse(a.warehouse)
  )
);

create policy "documents_delete_scoped"
on public.documents for delete
to authenticated
using (
  exists (
    select 1
    from public.activities a
    where a.id = documents.activity_id
      and public.can_access_warehouse(a.warehouse)
  )
);

drop policy if exists "charges_select_owner" on public.charges;
drop policy if exists "charges_insert_owner" on public.charges;
drop policy if exists "charges_update_owner" on public.charges;
drop policy if exists "charges_delete_owner" on public.charges;
drop policy if exists "public charges insert" on public.charges;
drop policy if exists "public charges delete" on public.charges;

create policy "charges_select_owner"
on public.charges for select
to authenticated
using (public.current_profile_role() = 'owner');

create policy "charges_insert_owner"
on public.charges for insert
to authenticated
with check (public.current_profile_role() = 'owner');

create policy "charges_update_owner"
on public.charges for update
to authenticated
using (public.current_profile_role() = 'owner')
with check (public.current_profile_role() = 'owner');

create policy "charges_delete_owner"
on public.charges for delete
to authenticated
using (public.current_profile_role() = 'owner');

create or replace view public.inventory_summary
with (security_invoker = true)
as
select
  product,
  warehouse,
  coalesce(sum(pieces) filter (where activity_date < current_date), 0) as in_qty,
  coalesce(abs(sum(pieces) filter (where activity_date >= current_date and pieces < 0)), 0) as reserved_qty,
  coalesce(sum(pieces) filter (where activity_date >= current_date and pieces > 0), 0) as incoming_qty
from public.activities
group by product, warehouse;

grant select on public.inventory_summary to authenticated;

drop policy if exists "activity_documents_select_scoped" on storage.objects;
drop policy if exists "activity_documents_insert_scoped" on storage.objects;
drop policy if exists "activity_documents_update_scoped" on storage.objects;
drop policy if exists "activity_documents_delete_scoped" on storage.objects;
drop policy if exists "public activity documents insert" on storage.objects;
drop policy if exists "public activity documents delete" on storage.objects;

create policy "activity_documents_select_scoped"
on storage.objects for select
to authenticated
using (
  bucket_id = 'activity-documents'
  and exists (
    select 1
    from public.activities a
    where a.id::text = (storage.foldername(name))[1]
      and public.can_access_warehouse(a.warehouse)
  )
);

create policy "activity_documents_insert_scoped"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'activity-documents'
  and exists (
    select 1
    from public.activities a
    where a.id::text = (storage.foldername(name))[1]
      and public.can_access_warehouse(a.warehouse)
  )
);

create policy "activity_documents_update_scoped"
on storage.objects for update
to authenticated
using (
  bucket_id = 'activity-documents'
  and exists (
    select 1
    from public.activities a
    where a.id::text = (storage.foldername(name))[1]
      and public.can_access_warehouse(a.warehouse)
  )
)
with check (
  bucket_id = 'activity-documents'
  and exists (
    select 1
    from public.activities a
    where a.id::text = (storage.foldername(name))[1]
      and public.can_access_warehouse(a.warehouse)
  )
);

create policy "activity_documents_delete_scoped"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'activity-documents'
  and exists (
    select 1
    from public.activities a
    where a.id::text = (storage.foldername(name))[1]
      and public.can_access_warehouse(a.warehouse)
  )
);
