create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sku text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.suppliers enable row level security;

drop policy if exists "products_select_scoped" on public.products;
drop policy if exists "products_insert_owner" on public.products;
drop policy if exists "products_update_owner" on public.products;
drop policy if exists "products_delete_owner" on public.products;

create policy "products_select_scoped"
on public.products for select
to authenticated
using (active = true or public.current_profile_role() = 'owner');

create policy "products_insert_owner"
on public.products for insert
to authenticated
with check (public.current_profile_role() = 'owner');

create policy "products_update_owner"
on public.products for update
to authenticated
using (public.current_profile_role() = 'owner')
with check (public.current_profile_role() = 'owner');

create policy "products_delete_owner"
on public.products for delete
to authenticated
using (public.current_profile_role() = 'owner');

drop policy if exists "customers_select_scoped" on public.customers;
drop policy if exists "customers_insert_owner" on public.customers;
drop policy if exists "customers_update_owner" on public.customers;
drop policy if exists "customers_delete_owner" on public.customers;

create policy "customers_select_scoped"
on public.customers for select
to authenticated
using (active = true or public.current_profile_role() = 'owner');

create policy "customers_insert_owner"
on public.customers for insert
to authenticated
with check (public.current_profile_role() = 'owner');

create policy "customers_update_owner"
on public.customers for update
to authenticated
using (public.current_profile_role() = 'owner')
with check (public.current_profile_role() = 'owner');

create policy "customers_delete_owner"
on public.customers for delete
to authenticated
using (public.current_profile_role() = 'owner');

drop policy if exists "suppliers_select_scoped" on public.suppliers;
drop policy if exists "suppliers_insert_owner" on public.suppliers;
drop policy if exists "suppliers_update_owner" on public.suppliers;
drop policy if exists "suppliers_delete_owner" on public.suppliers;

create policy "suppliers_select_scoped"
on public.suppliers for select
to authenticated
using (active = true or public.current_profile_role() = 'owner');

create policy "suppliers_insert_owner"
on public.suppliers for insert
to authenticated
with check (public.current_profile_role() = 'owner');

create policy "suppliers_update_owner"
on public.suppliers for update
to authenticated
using (public.current_profile_role() = 'owner')
with check (public.current_profile_role() = 'owner');

create policy "suppliers_delete_owner"
on public.suppliers for delete
to authenticated
using (public.current_profile_role() = 'owner');

drop policy if exists "activities_update_scoped" on public.activities;

create policy "activities_update_scoped"
on public.activities for update
to authenticated
using (public.can_access_warehouse(warehouse))
with check (public.can_access_warehouse(warehouse));
